## PDF table extraction

This notebook loads **`sample-tables.pdf`** from the **current working directory** (run with the repo root as cwd, or adjust `pdf_path` below).

**Requirements:** Python 3.13+, [`img2table`](https://pypi.org/project/img2table/), **Tesseract** on `PATH` with **`eng`** trained data (see `lang=` on `TesseractOCR`). Install notebook deps with `uv sync --group notebook` (see `pyproject.toml`).

In [5]:
from img2table.document import PDF
from img2table.ocr import TesseractOCR
from IPython.display import display_html

In [6]:
from pathlib import Path

pdf_path = Path("sample-tables.pdf")
if not pdf_path.is_file():
    raise FileNotFoundError(
        f"Missing {pdf_path.resolve()}. Add the file or set the kernel cwd to the directory that contains it."
    )

doc = PDF(str(pdf_path))

ocr = TesseractOCR(n_threads=1, lang="eng")

# Table extraction
extracted_tables = doc.extract_tables(
    ocr=ocr,
    implicit_rows=False,
    implicit_columns=False,
    borderless_tables=False,
    min_confidence=50,
)

tesseract 4.1.1
 leptonica-1.82.0
  libgif 5.1.9 : libjpeg 8d (libjpeg-turbo 2.1.1) : libpng 1.6.37 : libtiff 4.3.0 : zlib 1.2.11 : libwebp 1.2.2 : libopenjp2 2.4.0
 Found AVX2
 Found AVX
 Found FMA
 Found SSE
 Found libarchive 3.6.0 zlib/1.2.11 liblzma/5.2.5 bz2lib/1.0.8 liblz4/1.9.3 libzstd/1.4.8

In [7]:
extracted_tables

{0: [ExtractedTable(title=Table 1, bbox=(235, 565, 1465, 706),shape=(3, 3)),
  ExtractedTable(title=Table 2: example of footnotes referenced from within a table, bbox=(235, 841, 1465, 1311),shape=(8, 4)),
  ExtractedTable(title=Table 3: "film credits" style layout, bbox=(468, 1576, 1232, 1860),shape=(6, 2))],
 1: [ExtractedTable(title=Table 4: table 3 with column headers added, bbox=(468, 317, 1232, 648),shape=(7, 2)),
  ExtractedTable(title=Table 5: year-end financial statement (£, thousands), bbox=(235, 843, 1465, 1266),shape=(9, 4)),
  ExtractedTable(title=Table 6: a table with a more serious headings problem, bbox=(235, 1439, 1465, 1897),shape=(9, 5))],
 2: [ExtractedTable(title=Table 7: year-end statement, non-current assets (£, thousands), bbox=(235, 267, 1465, 461),shape=(4, 4)),
  ExtractedTable(title=Table 8: year-end statement, current assets (£, thousands), bbox=(235, 596, 1465, 799),shape=(4, 4)),
  ExtractedTable(title=Table 9: rainfall by continent, 2009, bbox=(235, 933, 1465, 1122),shape=(4, 5))],
 3: [ExtractedTable(title=Table 10: self-contained year-end statement (£, thousands) (multiple
  layout problems), bbox=(235, 317, 1465, 992),shape=(14, 5)),
  ExtractedTable(title=Table 11: self-contained year-end statement (£, thousands) (multiple
  problems resolved), bbox=(235, 1176, 1465, 1776),shape=(12, 4))],
 4: [ExtractedTable(title=Table 12: merged data cells are not recommended, bbox=(235, 267, 1465, 540),shape=(5, 5)),
  ExtractedTable(title=Table 13: use of graphic symbols, bbox=(235, 674, 1465, 863),shape=(4, 4)),
  ExtractedTable(title=Table 14: symbols replaced by real text, bbox=(235, 998, 1465, 1187),shape=(4, 4)),
  ExtractedTable(title=Table 15: courses offered by Institution X. A = Bachelor of Science,
  B = Bachelor of Arts, C = Masters, D = Doctorate, E = Diploma, bbox=(235, 1372, 1471, 1726),shape=(7, 5))],
 5: [ExtractedTable(title=Table 16: Masters courses offered by Institution X, bbox=(235, 301, 1471, 642),shape=(7, 5)),
  ExtractedTable(title=Table 17: accounts, 2011 (£, thousands), bbox=(235, 777, 1372, 1300),shape=(11, 3)),
  ExtractedTable(title=Table 18: accounts, 2011 (£, thousands), bbox=(235, 1434, 1372, 1987),shape=(11, 3))],
 6: [ExtractedTable(title=Table 19: Human Development Index (HDI)
  trends, 1980 to 2010. Source: Barro-Lee March, 2010, bbox=(235, 317, 1195, 712),shape=(6, 5)),
  ExtractedTable(title=Table 20: footnotes referenced from within a table, bbox=(235, 847, 1465, 1317),shape=(8, 4))],
 7: [ExtractedTable(title=Table 21: footnotes replaced by additional table summary text, bbox=(235, 267, 1465, 738),shape=(8, 4)),
  ExtractedTable(title=Table 22: referencing multiple endnotes from within a table, bbox=(235, 872, 1465, 1360),shape=(8, 4)),
  ExtractedTable(title=Table 23: simulated table created using tabs and containing no
  structure, bbox=(234, 1544, 1464, 1764),shape=(4, 5))],
 8: [ExtractedTable(title=Table 24: year-end financial statement (£, thousands), bbox=(235, 267, 1465, 884),shape=(13, 4)),
  ExtractedTable(title=Table 25: setting column and row scope via the tags panel, bbox=(235, 1019, 1465, 1288),shape=(5, 5)),
  ExtractedTable(title=Table 26: courses offered by Institution X. A = Bachelor of Science,
  B = Bachelor of Arts, C = Masters, D = Doctorate, E = Diploma, bbox=(235, 1473, 1392, 1806),shape=(7, 5))],
 9: [ExtractedTable(title=Table 27: “table” with columns simulated by using tab stops, bbox=(235, 267, 1465, 456),shape=(4, 3)),
  ExtractedTable(title=Table 28: year-end financial table (£, thousands) – headings problem
  revisited, bbox=(235, 641, 1465, 1261),shape=(13, 4))],
 10: [ExtractedTable(title=Table 29: multiple headers attributes for each data cell, bbox=(235, 267, 1465, 915),shape=(13, 5))]}

### Render extracted tables

The next cell prints each `ExtractedTable` as HTML via `table.html_repr(...)`.

In [8]:
for page, tables in extracted_tables.items():
    for idx, table in enumerate(tables):
        display_html(table.html_repr(title=f"Page {page + 1} - Extracted table n°{idx + 1}"), raw=True)

,0,1,2
0,Column header (TH),Column header (TH),Column header (TH)
1,Row header (TH),Data cell (TD),Data cell (TD)
2,Row header(TH),Data cell (TD),Data cell (TD)

,0,1,2,3
0,Expenditure by function £ million,Expenditure by function £ million,2009/10,2010/11 1
1,Policy functions,Financial,22.5,30.57
2,Policy functions,Information 2,10.2,14.8
3,Policy functions,Contingency,2.6,1.2
4,Remunerated functions,Agency services 3,44.7,35.91
5,Remunerated functions,Payments,22.41,19.88
6,Remunerated functions,Banking,22.90,44.23
7,Remunerated functions,Other,12.69,10.32

,0,1
0,Main character,Daniel Radcliffe
1,Sidekick 1,Rupert Grint
2,Sidekick 2,Emma Watson
3,Lovable ogre,Robbie Coltrane
4,Professor,Maggie Smith
5,Headmaster,Richard Harris

,0,1
0,Role,Actor
1,Main character,Daniel Radcliffe
2,Sidekick 1,Rupert Grint
3,Sidekick 2,Emma Watson
4,Lovable ogre,Robbie Coltrane
5,Professor,Maggie Smith
6,Headmaster,Richard Harris

,0,1,2,3
0,2010 2009 2008,2010 2009 2008,2010 2009 2008,2010 2009 2008
1,Non-current assets,Non-current assets,Non-current assets,Non-current assets
2,Property,345,445,222
3,Investment,567,654,423
4,Intangibles,423,123,453
5,Current assets,Current assets,Current assets,Current assets
6,Trade and other receivables,435,634,231
7,Cash and cash equivalents,524,123,482
8,Other,223,211,254

,0,1,2,3,4
0,Rainfall\n(inches),Americas,Asia,Europe,Africa
1,2010,2010,2010,2010,2010
2,Average,104,201,193,144
3,24 hour high,15,26,27,18
4,12 hour high,9,10,11,12
5,2009,2009,2009,2009,2009
6,Average,133,244,155,166
7,24 hour high,27,28,29,20
8,12 hour high,11,12,13,16

,0,1,2,3
0,Non-current assets,2010,2009,2008
1,Property,345,445,222
2,Investment,567,654,423
3,Intangibles,423,123,453

,0,1,2,3
0,Current assets,2010,2009,2008
1,Trade and other receivables,435,634,231
2,Cash and cash equivalents,524,123,482
3,Other,223,211,254

,0,1,2,3,4
0,Rainfall (inches),Americas,Asia,Europe,Africa
1,Average,133,244,155,166
2,24 hour high,27,28,29,20
3,12 hour high,11,12,13,16

,0,1,2,3,4
0,NaN,2011,2011,2010 restated,2010 restated
1,General income,NaN,"250,000",NaN,"200,000"
2,"Increase in value, WIP",NaN,"15,000",NaN,"30,000"
3,NaN,NaN,"265,000",NaN,"230,000"
4,Administrative costs,Administrative costs,Administrative costs,Administrative costs,Administrative costs
5,Staff costs,"(200,000)",NaN,"(150,000)",NaN
6,Early departures,"(10,000)",NaN,"(20,000)",NaN
7,Other,"(25,000)",NaN,"(10,000)",NaN
8,Depreciation,"(10,000)",NaN,"(10,000)",NaN
9,Programme costs,Programme costs,Programme costs,Programme costs,Programme costs
10,Impairment loss,"(10,000)",NaN,"(5,000)",NaN
11,Other,"(5,000)",NaN,"(5,000)",NaN
12,NaN,"(260,000)",NaN,"(200,000)",NaN
13,Surplus,NaN,"5,000",NaN,"30,000"

,0,1,2,3
0,NaN,NaN,2011,2010 restated
1,Income,General income,"250,000","200,000"
2,Income,Increase in value,"15,000","30,000"
3,Income,Total income,"265,000","230,000"
4,Administrative costs,Staff costs,"(200,000)","(150,000)"
5,Administrative costs,Early departures,"(10,000)","(20,000)"
6,Administrative costs,Other operating costs,"(25,000)","(10,000)"
7,Administrative costs,Depreciation,"(10,000)","(10,000)"
8,Programme costs,Impairment loss,"(10,000)","(5,000)"
9,Programme costs,Other,"(5,000)","(5,000)"
10,Programme costs,Total costs,"(260,000)","(200,000)"
11,Surplus,Surplus,"5,000","30,000"

,0,1,2,3,4
0,NaN,2008,2008,2009,2009
1,Name,Yes,No,Yes,No
2,Bob,2,5,6,7
3,Sue,3,8,4,7
4,Sam,[data relating to both columns in\na single cell spanning both],[data relating to both columns in\na single cell spanning both],[data relating to both columns in\na single cell spanning both],[data relating to both columns in\na single cell spanning both]

,0,1,2,3
0,Question,Respondent A,Respondent B,Respondent C
1,Are you a UK citizen?,,,
2,Are you currently employed?,,,
3,Do you have a driving licence?,,,

,0,1,2,3
0,Question,Respondent A,Respondent B,Respondent C
1,Are you a UK citizen?,No,Yes,No
2,Are you currently employed?,Yes,No,Yes
3,Do you have a driving licence?,No,No,Yes

,0,1,2,3,4
0,NaN,2006,2007,2008,2009
1,Economics,"A, B","A, C","A, B","A, C"
2,International relations,"A, E","A, E","A, B","A, E"
3,Philosophy,A,A,A,"A, D"
4,Politics,"A, D","A, D","A, D",A
5,Mathematics,"B, C",B,"A, E","A, B"
6,English,"A, C","A, B","A,B",C

,0,1,2,3,4
0,NaN,2006,2007,2008,2009
1,Economics,No,Yes,Yes,Yes
2,International relations,No,No,No,No
3,Philosophy,No,No,No,No
4,Politics,No,No,No,No
5,Mathematics,Yes,No,No,No
6,English,Yes,Yes,Yes,Yes

,0,1,2
0,Accounting item,Accounting item,2011
1,Income,General income,"200,000"
2,Income,"Increase in value, WIP","30,000"
3,Income,Income subtotal,"230,000"
4,Administrative costs,Staff,"150,000"
5,Administrative costs,Early departures,"20,000"
6,Administrative costs,Other operating costs,"10,000"
7,Administrative costs,Depreciation,"10,000"
8,Programme costs,Impairment loss,"10,000"
9,Programme costs,Costs subtotal,"200,000"
10,Balance,Balance,"30,000"

,0,1,2
0,Accounting item,Accounting item,2011
1,Income,General income,"200,000"
2,Income,"Increase in value, WIP","30,000"
3,Income,Income subtotal,"230,000"
4,Administrative costs,Staff,"(150,000)"
5,Administrative costs,Early departures,"(20,000)"
6,Administrative costs,Other operating costs,"(10,000)"
7,Administrative costs,Depreciation,"(10,000)"
8,Programme costs,Impairment loss,"(10,000)"
9,Programme costs,Costs subtotal,"(200,000)"
10,Balance,Balance,"30,000"

,0,1,2,3,4
0,Country,1980,1990,2000,2010
1,Afghanistan,0.78,1.48,2.16,3.33
2,Albania,8.89,9.67,9.89,10.38
3,Algeria,4.74,3.33,5.50,7.24
4,Andorra,4.98,5.63,9.09,10.35
5,Angola,-,-,4.42,4.42

,0,1,2,3
0,Expenditure by function £million,Expenditure by function £million,2009/10,2010/11 1
1,Policy functions,Financial,22.5,30.57
2,Policy functions,Information 2,10.2,14.8
3,Policy functions,Contingency,2.6,1.2
4,Remunerated functions,Agency services 3,44.7,35.91
5,Remunerated functions,Payments,22.41,19.88
6,Remunerated functions,Banking,22.90,44.23
7,Remunerated functions,Other,12.69,10.32

,0,1,2,3
0,Expenditure by function £million,Expenditure by function £million,2009/10,2010/11
1,Policy functions,Financial,22.5,30.57
2,Policy functions,Information,10.2,14.8
3,Policy functions,Contingency,2.6,1.2
4,Remunerated functions,Agency services,44.7,35.91
5,Remunerated functions,Payments,22.41,19.88
6,Remunerated functions,Banking,22.90,44.23
7,Remunerated functions,Other,12.69,10.32

,0,1,2,3
0,Expenditure £m,Notes\n(Notes located on page [n]),2010,2011
1,Information,1,10.2,14.8
2,Contingency,NaN,2.6,1.2
3,Payments,3,22.41,19.88
4,Banking services,4,22.90,44.23
5,Interest,NaN,0.23,0.10
6,Dividends,23,2.5,3.68
7,Other,9,12.69,10.32

,0,1,2,3,4
0,NaN,2008,2008,2009,2009
1,Name,Entered,Completed,Entered,Completed
2,Bob,22,21,20,19
3,Sue,44,12,12,10

,0,1,2,3
0,2010 2009 2008,2010 2009 2008,2010 2009 2008,2010 2009 2008
1,Non-current assets,Non-current assets,Non-current assets,Non-current assets
2,Buildings,345,445,222
3,Investment,567,654,423
4,Intangibles,423,123,453
5,Current assets,Current assets,Current assets,Current assets
6,Trade,435,634,231
7,Cash,524,123,482
8,Other,223,211,254
9,Current liabilities,Current liabilities,Current liabilities,Current liabilities
10,Trade liabilities,154,125,421
11,Financial debt,231,474,572
12,Provisions,111,312,347

,0,1,2,3,4
0,NaN,2008,2008,2009,2009
1,Name,Entered,Won,Entered,Won
2,Bob,22,21,20,19
3,Sue,44,12,12,10
4,Sam,16,4,45,30

,0,1,2,3,4
0,NaN,2006,2007,2008,2009
1,Economics,"A, B","A, C","A, C","A, C"
2,International relations,"A, E","A, E","A, B","A, B"
3,Philosophy,A,A,A,A
4,Politics,"A, D","A, D","A, B",A
5,Mathematics,"B, C",B,"A, B","A, B"
6,English,"A, C","A, B","A,B","A, C"

,0,1,2
0,Name,Apples,Pears
1,Bob Scott,20,25
2,"Susan. P. Arnold-Jones, BA, FRSA, MD",24,15
3,Sam Holder-Dickinson,14,10

,0,1,2,3
0,2010 2009 2008,2010 2009 2008,2010 2009 2008,2010 2009 2008
1,Non-current assets,Non-current assets,Non-current assets,Non-current assets
2,Buildings,345,445,222
3,Investment,567,654,423
4,Intangibles,423,123,453
5,Current assets,Current assets,Current assets,Current assets
6,Trade,435,634,231
7,Cash,524,123,482
8,Other,223,211,254
9,Current liabilities,Current liabilities,Current liabilities,Current liabilities
10,Trade liabilities,154,125,421
11,Financial debt,231,474,572
12,Provisions,111,312,347

,0,1,2,3,4
0,NaN,South America,Asia,Africa,Australia
1,2010,2010,2010,2010,2010
2,Highest average,523.6,467.4,405.0,340.5
3,Highest in 24 hours,73.1,54.1,27.2,66.3
4,Highest in 12 hours,42.4,30.1,15.9,40.3
5,2009,2009,2009,2009,2009
6,Highest average,487.7,453.6,398.7,356
7,Highest in 24 hours,67.2,53.2,44.3,53.8
8,Highest in 12 hours,34.7,34.1,29.8,31.0
9,2008,2008,2008,2008,2008
10,Highest average,496.7,444.3,502.1,399.6
11,Highest in 24 hours,44.2,56.7,32.1,63.2
12,Highest in 12 hours,30.1,32.7,21.9,40.2